[package]
name = "cscript"
version = "0.3.0"
edition = "2024"

[dependencies]
chumsky = "0.11.1"
clap = { version = "4.5.47", features = ["derive"] }
inkwell = { version = "0.6.0", features = ["llvm18-1"] }
logos = "0.15.1"
miette = { version = "7.6.0", features = ["fancy"] }
thiserror = "2.0.16"
